# Generated by Django 4.2.16 on 2024-09-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('convo_id', models.BigIntegerField()),
                ('sender', models.CharField(max_length=50)),
                ('message_content', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('profile', models.ImageField(default='images/default-profile.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('convo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message_app.conversation')),
                ('receiver_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_username', to='message_app.users', to_field='username')),
                ('sender_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_username', to='message_app.users', to_field='username')),
            ],
        ),
    ]
