# Generated by Django 4.2.16 on 2024-10-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='message_id',
            new_name='id_fk',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver_name',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='convo_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='message',
            name='convo_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convo_id_fk', to='message_app.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_convo_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='convo_id',
            field=models.IntegerField(null=True),
        ),
    ]
