# Generated by Django 4.2.16 on 2024-10-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_rename_message_id_conversation_id_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_username', to='message_app.users', to_field='username'),
        ),
    ]
