# Generated by Django 4.2.16 on 2024-10-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
    ]
