# Generated by Django 4.2.16 on 2024-10-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0005_conversation_receiver_conversation_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
    ]
