# Generated by Django 4.2.16 on 2024-10-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0006_remove_conversation_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
