# Generated by Django 4.2.16 on 2024-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0007_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
