# Generated by Django 4.2.16 on 2024-10-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0009_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
