# Generated by Django 4.2.16 on 2024-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0011_alter_conversation_table_alter_message_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='online', max_length=10, null=True),
        ),
    ]
