# Generated by Django 4.2.16 on 2024-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0012_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='online', max_length=10),
        ),
    ]
