# Generated by Django 4.2.16 on 2024-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0014_alter_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
