# Generated by Django 4.2.16 on 2024-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0015_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
