# Generated by Django 5.1.2 on 2024-11-05 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0017_conversation_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='id_fk',
            new_name='message_id_fk',
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
