# Generated by Django 5.1.2 on 2024-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0019_alter_conversation_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
