# Generated by Django 5.1.2 on 2024-11-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0021_conversation_receiver_conversation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='message_id_fk',
            new_name='message_content_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_convo_id',
            new_name='convo_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='messages_id',
        ),
    ]
