# Generated by Django 5.1.2 on 2024-11-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0022_rename_message_id_fk_conversation_message_content_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
