# Generated by Django 5.1.2 on 2024-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0025_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
