# Generated by Django 5.1.2 on 2024-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0026_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='convo_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
