# Generated by Django 5.1.2 on 2024-11-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0027_alter_conversation_convo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
