# Generated by Django 5.1.2 on 2024-11-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0028_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message_content',
            field=models.CharField(max_length=500),
        ),
    ]
