# Generated by Django 5.1.2 on 2024-11-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0029_alter_conversation_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message_content',
            field=models.CharField(max_length=1000),
        ),
    ]
