# Generated by Django 5.1.3 on 2024-11-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='request_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
