# Generated by Django 5.1.3 on 2024-11-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0035_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_content',
        ),
    ]
