# Generated by Django 5.1.3 on 2024-11-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0036_rename_message_notification_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='message_app.users', to_field='username'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request_from',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
