# Generated by Django 5.1.3 on 2024-11-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0038_alter_notification_notif_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_fk',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='message_app.users'),
        ),
    ]
